name: flutter_classroom_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.3
  shared_preferences: ^2.1.0
  awesome_notifications: ^0.7.4+1
  flutter_slidable: ^3.0.0
  intl: ^0.17.0
  url_launcher: ^6.1.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/

